server:
  port: 8080

spring:
  application:
    name: message-plus

  jpa:
    hibernate:
      ddl-auto: none     # let flyway do the work
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  flyway:
    enabled: true

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://messageplus-8ivdgq.us1.zitadel.cloud/oauth/v2/keys

management:
  endpoints.web.exposure.include: health,info

app:
  openai:
    api-key: ${OPENAI_API_KEY}
